name: PR

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  PR333:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: CONTENT BRANCH-333
        run: |
          echo 33333333
          echo THIS IS BRANCH-333