name: PR

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  PR:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: CONTENT BRANCH-22
        run: |
          echo THIS IS BRANCH-22
          echo action from $(git rev-parse --abbrev-ref HEAD)