name: PR

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  PR44444:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: CONTENT BRANCH-4444
        run: |
          echo 44444444
          echo THIS IS BRANCH-4444